services:
  db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coursemaster
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/coursemaster
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      ./wait-for-db.sh && sh -c "
      if [ $(npx prisma migrate status | grep 'Database is already up to date' | wc -l) -eq 0 ]; then
        npx prisma migrate dev --name 'init';
      fi
      npm run start:dev"
volumes:
  db_data:
